<h1 class="ut-heading ut-heading--h1">Danksagung</h1>
<p>Das Projekt wurde mit Hilfe einer großzügigen Förderung durch die Deutsche Forschungsgemeinschaft zwischen 2016-2018 an der Universitätsbibliothek Tübingen durchgeführt.</p>
<p>Dank gilt weiter der Malayalam-Wikimedia-Gruppe um Shiju Alex, die das Projekt angestoßen und aktiv bei der Erstellung durchsuchbarer Unicodetexte mitgewirkt hat.</p>
<p>Für die digitalisierten und publizierten Bilder der Handschriften und Drucke liegt das Copyright – wenn nichts anderes vermerkt – bei der Universitätsbibliothek Tübingen.</p>
