<h1 class="ut-heading ut-heading--h1">Acknowledgements</h1>
<p>The project was carried out with the help of a generous grant from the German Research Foundation at Tübingen University Library from 2016-2018.</p>
<p>Thanks also go to Shiju Alex's Malayalam Wikimedia group, who initiated the project and actively contributed to the creation of searchable Unicode texts.</p>
<p>Unless otherwise noted, the copyright for the digitised and published images of manuscripts and prints is held by Tübingen University Library.</p>
