<h1 class="ut-heading ut-heading--h1">###DT-digitization_standards###</h1>
<ul>
    <li><a target="_blank" href="http://www.loc.gov/standards/mets/">Metadata Encoding and Transmission Standard (METS)</a></li>
    <li><a target="_blank" href="http://digitizationguidelines.gov">Federal Agencies Digitization Guidelines Initiative</a></li>
    <li><a target="_blank" href="http://www.loc.gov/standards/mods/">Metadata Object Description Schema (MODS)</a></li>
    <li><a target="_blank" href="http://www.tei-c.org/index.xml">Text Encoding Initiative (TEI)</a></li>
    <li><a target="_blank" href="http://www.ub.uni-heidelberg.de/Englisch/helios/digi/dwork.html">DWork – Heidelberg Digitization Workflow</a></li>
</ul>

<h1 class="ut-heading ut-heading--h1">###DT-digital_mapping_platforms###</h1>
<ul>
    <li><a target="_blank" href="http://neatline.org">Neatline</a></li>
    <li><a target="_blank" href="http://www.indologie-carnatica.uni-tuebingen.de">Digital Edition of Epigraphia Carnatica</a></li>
    <li><a target="_blank" href="http://commons.pelagios.org">Pelagios</a></li>
</ul>
