<h1 class="ut-heading ut-heading--h1">Digital Catalogues</h1>
<ul>
    <li><a href="https://www.ixtheo.de/Search/Results?lookfor=gundert%2C+hermann&type=AllFields">Literature by and about Hermann Gundert</a></li>
    <li><a href="http://libguides.bodleian.ox.ac.uk/c.php?g=422971&p=2888532">Bodleian Libraries – Oriental Manuscripts &amp; Rare Books: South and Inner Asia</a></li>
    <li><a href="http://dla.library.upenn.edu/dla/medren/search.html?fq=collection_facet%3A%22Indic%20Manuscripts%22">Penn in Hand: Selected Manuscripts (Indic)</a></li>
    <li><a href="http://catalogues.indology.info">Online Library of Digitized Sanskrit and Prakrit Manuscript Catalogues</a></li>
    <li><a href="http://www.sanskrit-lexicon.uni-koeln.de/scans/ACCScan/2013/web/index.php">Aufrecht’s Catalogus Catalogorum (on the Cologne Digital Sanskrit Dictionaries website)</a></li>
    <li><a href="http://eap.bl.uk">Endangered Archive Program – EAP676: Survey of Buddhist Sanskrit Manuscripts</a></li>
    <li><a href="http://sauc.uchicago.edu/about.html">South Asia Union Catalogue</a></li>
    <li><a href="http://cudl.lib.cam.ac.uk/collections/sanskrit">Sanskrit Manuscript Project, Cambridge</a></li>
</ul>
