<h1 class="ut-heading ut-heading--h1">###PAGE_TITLE###</h1>
<a class="ut-link ut-link--external ut-link--block ut-link--context-icon" target="_blank" href="http://gretil.sub.uni-goettingen.de">GRETIL - Göttingen Register of Electronic Texts in Indian Languages</a>
<a class="ut-link ut-link--external ut-link--block ut-link--context-icon" target="_blank" href="http://sarit.indology.info/exist/apps/sarit/works/">SARITSEARCH AND RETRIEVAL OF INDIC TEXTS</a>
<a class="ut-link ut-link--external ut-link--block ut-link--context-icon" target="_blank" href="http://muktalib5.org/digital_library_secure_entry.htm">Muktabodha Indological Research Institute</a>
<a class="ut-link ut-link--external ut-link--block ut-link--context-icon" target="_blank" href="http://titus.uni-frankfurt.de/indexe.htm">Thesaurus Indogermanischer Text- und Sprachmaterialien (TITUS)</a>
<a class="ut-link ut-link--external ut-link--block ut-link--context-icon" target="_blank" href="http://idb.ub.uni-tuebingen.de/opendigi/EC">Epigraphia Carnatica/Epigrāphiya Karnāṭaka</a>
