<h1 class="ut-heading ut-heading--h1">E-texts</h1>
<ul>
    <li><a href="http://gretil.sub.uni-goettingen.de">GRETIL - Göttingen Register of Electronic Texts in Indian Languages</a></li>
    <li><a href="http://sarit.indology.info/exist/apps/sarit/works/">SARITSEARCH AND RETRIEVAL OF INDIC TEXTS</a></li>
    <li><a href="http://muktalib5.org/digital_library_secure_entry.htm">Muktabodha Indological Research Institute</a></li>
    <li><a href="http://titus.uni-frankfurt.de/indexe.htm">Thesaurus Indogermanischer Text- und Sprachmaterialien (TITUS)</a></li>
    <li><a href="http://idb.ub.uni-tuebingen.de/diglit/EC">Epigraphia Carnatica/Epigrāphiya Karnāṭaka</a></li>
</ul>
