<h1 class="ut-heading ut-heading--h1">###PAGE_TITLE###</h1>
<h2 class="ut-heading ut-heading--h2">Printed (partly lithographed) works</h2>
<p>
<ul class="ut-list">
    <li>252 Malayalam</li>
    <li>161 Kannada</li>
    <li>3 Telegu</li>
    <li>12 Tamil</li>
</ul>
</p>
<p>Around 50 works in German or English by Hermann Gundert and missionary colleagues; circa 80 articles from missionary periodicals by Hermann Gundert and colleagues on various topics concerning South India and the South Indian Mission.</p>

<h2 class="ut-heading ut-heading--h2">Manuscripts</h2>
<p>
<ul class="ut-list">
    <li>99 Malayalam manuscripts, partly notes and drafts in Malayalam by Hermann Gundert,</li>
    <ul><li>including 20 palm-leaf manuscripts (or respectively one manuscript on Talipot leaves)</li></ul>
    <li>36 Kannada manuscripts</li>
    <ul><li>including 2 palm-leaf manuscripts</li></ul>
    <li>3 Tamil manuscripts on paper</li>
</ul>
</p>

<h2 class="ut-heading ut-heading--h2">Malayalam OCR</h2>
<p>In cooperation with Shiju Alex (Malayalam Wikimedia Community) and a staff of Indian assistants, 252 Malayalam prints will have been transferred into machine-readable Malayalam by the end of the project.</p>

<p>To date, <b>823</b> titles with approximately <b>136,500</b> pages have been digitised, of which 218 titles (37,714 pages) are already available online with the remainder in various stages of post-processing.</p>
<p>(As at 15<sup>th</sup> May 2018)</p>
