<h1 class="ut-heading ut-heading--h1">###PAGE_TITLE###</h1>
<h2 class="ut-heading ut-heading--h2">Gedruckte Werke</h2>
<p>
<ul class="ut-list">
    <li>252 Titel in Malayalam-Schrift</li>
    <li>161 Titel in Kannada-Schrift</li>
    <li>3 Titel in Telugu-Schrift</li>
    <li>12 Titel in Tamil-Schrift</li>
    <li>340 Titel auf Deutsch oder Englisch, davon ca 190 Aufsätze aus Zeitschriften</li>
</ul>
</p>

<h2 class="ut-heading ut-heading--h2">Abschriften in maschinenlesbarem Malayalam</h2>
<p>
    In Zusammenarbeit mit Shiju Alex und den Interessierten der ‚Kerala Archives Interest Group‘ sowie einem Stab von Hilfskräften in Kerala, wurden die Malayalam-Drucke in maschinenlesbares Malayalam transkribiert und den Digitalisaten hinzugefügt.
</p>

<h2 class="ut-heading ut-heading--h2">Handschriften</h2>
<p>
<ul class="ut-list">
    <li>99 in Malayalam-Schrift geschriebene, darunter 20 Palmblatt Handschriften</li>
    <li>36 in Kannaḍa-Schrift geschriebene, darunter 2 Palmblatt-Handschriften,</li>
    <li>3 in Tamil-Schrift geschriebene Handschriften</li>
</ul>
</p>

<h2 class="ut-heading ut-heading--h2">Gesamtzahlen</h2>
<p>Insgesamt wurden 136.500 Seiten digitalisiert, die sich auf 823 Titel verteilen. Darüberhinaus wurden xxxxx Seiten von den indischen Projektpartnern in maschinenlesbares Malayalam abgeschrieben.</p>
