<h1 class="ut-heading ut-heading--h1">###DT-facts_and_figures###</h1>
<p><b>(as at 15.05.2018)</b></p>
<h2 class="ut-heading ut-heading--h2">Printed, lithograph or letter press works</h2>
<p>
<ul>
    <li>252 Malayalam</li>
    <li>161 Kannaḍa</li>
    <li>3 Telegu</li>
    <li>12 Tamil</li>
</ul>
</p>
<p>About 50 Books and pamphlets in German or English by Hermann Gundert or his missionary colleagues as well as <b>ca 80</b> articles from missionary periodicals written by Hermann Gundert and colleagues about different topics concerning South India and the south Indian mission.</p>

<h2 class="ut-heading ut-heading--h2">Manuscripts</h2>
<p>
<ul>
    <li>99 Malayalam manuscripts (partly notes and drafts by Hermann Gundert and others in Malayalam)</li>
    <ul><li>among them, 20 palm leaf manuscripts (resp. 1 Talipot manuscript)</li></ul>
    <li>36 Kannaḍa manuscripts </li>
    <ul><li>Among them 2 palm leave manuscripts</li></ul>
    <li>3 Tamil manuscripts on paper</li>
</ul>
</p>

<h2 class="ut-heading ut-heading--h2">Malayalam-OCR</h2>
<p>With the enthusiastic support from Shiju Alex and his Malayalam Wikimedia Community and the help of many Indian assistants, <b>252</b> Malayam printed works will be transferred into machine-readable Malayalam by the end of 2018.</p>

<p>So far <b>823</b> titles (ca <b>136.500</b> pages) were digitized. <b>218</b> titles (37.714 pages) are already, the rest is in different postprocessing stages.</p>
