<h1 class="ut-heading ut-heading--h1">###PAGE_TITLE###</h1>
<h2 class="ut-heading ut-heading--h2">Gedruckte Werke</h2>
<p>
<ul class="ut-list">
    <li>293 Titel in Malayalam-Schrift</li>
    <li>187 Titel in Kannaḍa-Schrift</li>
    <li>25 Titel in Tamil-Schrift</li>
    <li>4 Titel in Telugu-Schrift</li>
    <li>340 Titel auf Deutsch oder Englisch, davon ca 190 Aufsätze aus Zeitschriften</li>
</ul>
</p>

<h2 class="ut-heading ut-heading--h2">Abschriften in maschinenlesbarem Malayalam</h2>
<p>In Zusammenarbeit mit Shiju Alex und den Mitgliedern der ‚Kerala Archives Interest Group‘ sowie einem Stab von Hilfskräften in Kerala, wurden die Malayalam-Drucke in maschinenlesbares Malayalam transkribiert und den Digitalisaten hinzugefügt.</p>

<h2 class="ut-heading ut-heading--h2">Handschriften</h2>
<p>
<ul class="ut-list">
    <li>93 in Malayalam-Schrift geschriebene, darunter 20 Palmblatt Handschriften</li>
    <li>39 in Kannaḍa-Schrift geschriebene, darunter 2 Palmblatt-Handschriften,</li>
    <li>2 in Tamil-Schrift geschriebene Handschriften</li>
    <li>5 überwiegend auf Deutsch oder Englisch geschriebene Handschriften</li>
</ul>
</p>

<h2 class="ut-heading ut-heading--h2">Gesamtzahlen</h2>
<p>Insgesamt wurden 849 Titel, darunter 142 Handschriften, mit insgesamt 137.148 Seiten digitalisiert. Außerdem wurden knapp 23.500 Seiten von den indischen Projektpartnern in maschinenlesbares Malayalam abgeschrieben.</p>
