<h1 class="ut-heading ut-heading--h1">###DT-facts_and_figures###</h1>
<p><b>(Stand 15.05.2018)</b></p>
<h2 class="ut-heading ut-heading--h2">Gedruckte (teilweise lithographierte) Werke:</h2>
<p>
<ul>
    <li>252 Malayalam</li>
    <li>161 Kannada</li>
    <li>3 Telugu</li>
    <li>12 Tamil</li>
</ul>
</p>
<p>Ca 50 Werke auf Deutsch oder Englisch von Hermann Gundert und Missionarskollegen;<br/>
dazu <b>ca 80</b> Artikel aus Missionszeitschriften von Hermann Gundert und Kollegen zu verschiedenen Themen zu Südindien und der südindischen Mission.
</p>

<h2 class="ut-heading ut-heading--h2">Handschriftliches:</h2>
<p>
<ul>
    <li>99 Malayalam-Handschriften, teilweise Notizen und Entwürfe auf Malayalam von Hermann Gundert,</li>
    <ul><li>darunter 20 Handschriften auf Palmblatt (bzw. eine Hs auf Talipot-Blättern)</li></ul>
    <li>36 Kannada-Handschriften,</li>
    <ul><li>darunter 2 Palmblatt-Handschriften</li></ul>
    <li>3 Tamil-Handschriften auf Papier</li>
</ul>
</p>

<h2 class="ut-heading ut-heading--h2">Malayalam-OCR:</h2>
<p>In Zusammenarbeit mit Shiju Alex (Malayalam Wikimedia Community) und einem Stab von indischen Hilfskräften werden bis Projektende <b>252</b> Malayalam-Drucke in maschinenlesbares Malayalam abgeschrieben.</p>

<p>Bisher wurden <b>823</b> Titel mit ca <b>136.500</b> Seiten digitalisiert, davon sind 218 Titel (37.714 Seiten) bereits online verfügbar, der Rest befindet sich in verschiedenen Stadien der Nachbearbeitung.</p>
