<h1 class="ut-heading ut-heading--h1">###PAGE_TITLE###</h1>
<h2 class="ut-heading ut-heading--h2">Printed works</h2>
<p>
<ul class="ut-list">
    <li>252 titles in Malayalam script</li>
    <li>161 titles in Kannada script</li>
    <li>12 titles in Tamil script</li>
    <li>3 titles in Telegu script</li>
    <li>340 titles in German or English, including 190 articles from periodicals</li>
</ul>
</p>

<h2 class="ut-heading ut-heading--h2">Works transcribed into machine-readable Malayalam</h2>
<p>
    The works in Malayalam script were transcribed into machine-readable Malayalam in cooperation with Shiju Alex, the leader of the ‘Kerala Archives Interest Group’ and a staff of Indian assistants and volunteers and then added to the digitized objects.
</p>

<h2 class="ut-heading ut-heading--h2">Manuscripts</h2>
<p>
<ul class="ut-list">
    <li>99 manuscripts in Malayalam script, including 20 palm-leaf manuscripts</li>
    <li>36 manuscripts in Kannaḍa script, including 2 palm-leaf manuscripts</li>
    <li>3 manuscripts in Tamil script</li>
</ul>
</p>

<h2 class="ut-heading ut-heading--h2">Total Numbers</h2>
<p>136,500 pages from 823 titles have been digitised. In addition, xxxxx pages were transcribed by Indian collaborators into machine-readable Malayalam script.</p>
