<div class="ut-grid ut-grid--deck ut-grid--3333 ut-page-footer__quicklinks">
    <div class="ut-grid__col-12 ut-page-footer__col">
        <div class="ut-panel panel ut-panel--collapsing-only-mobile" id="footerpanel-4">
            <div class="ut-panel__heading ut-page-footer__heading" id="footerpanel-4-ph">
                <h6 class="ut-heading ut-panel__title"><a class="ut-link ut-panel__link" href="#footerpanel-4-pc" data-toggle="collapse" title="Panel öffnen/schließen">Kontakt<span class="ut-link__icon ut-link__icon--right ut-panel__icon ut-icon ut-icon-down-dir"></span></a></h6>
            </div>
            <div class="ut-panel__collapse collapse" id="footerpanel-4-pc">
                <div class="ut-panel__body ">
                    <address class="ut-page-footer__contact">
                        <strong>Universitätsbibliothek Tübingen</strong><br>Wilhelmstr. 32<br>72074 Tübingen<br>Tel: +49 (0) 7071 29-72577<br><a  class="ut-link ut-link--email ut-link--block ut-link--context-icon" href="mailto:gundert-portal@ub.uni-tuebingen.de" title="E-Mail senden">gundert-portal@ub.uni-tuebingen.de</a><br>
                    </address>
                </div>
            </div>
        </div>
    </div>
</div>

<hr class="ut-page-footer__devider hidden-xs">

<div class="row ut-page-footer__legal">
    <div class="col-xs-12 col-sm-6 col-md-6 ut-page-footer__copyright">
        <p class="ut-copyright">© 2018 Eberhard Karls Universität Tübingen, Tübingen</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 ut-page-footer__nav-meta">
        <nav class="ut-nav ut-nav--meta-bottom" aria-label="Metanavigation">
            <ul class="ut-nav__list ">
                <li class="ut-nav__item " data-level-count="1">
                    <a class="ut-link ut-nav__link" href="?page=imprint">Impressum</a>
                </li>
                <li class="ut-nav__item " data-level-count="2">
                    <a class="ut-link ut-nav__link" target="_blank" href="https://uni-tuebingen.de/meta/datenschutzerklaerung/">Datenschutzerklärung</a>
                </li>
                <li class="ut-nav__item " data-level-count="3">
                    <a class="ut-link ut-nav__link" href="?page=sitemap">Sitemap</a>
                </li>
            </ul>
        </nav>
    </div>
</div>
