<div class="ut-grid ut-grid--deck ut-grid--3333 ut-page-footer__quicklinks">
    <div class="ut-grid__col-1 ut-page-footer__col">
        <div class="ut-panel panel ut-panel--collapsing-only-mobile" id="footerpanel-1">
            <div class="ut-panel__heading ut-page-footer__heading" id="footerpanel-1-ph">
                <h6 class="ut-heading ut-panel__title"><a class="ut-link ut-panel__link" href="#footerpanel-1-pc" data-toggle="collapse" title="Panel öffnen/schließen">Service<span class="ut-link__icon ut-link__icon--right ut-panel__icon ut-icon ut-icon-down-dir"></span></a></h6>
            </div>
            <div class="ut-panel__collapse collapse" id="footerpanel-1-pc">
                <div class="ut-panel__body ">
                    <div class="ut-link-register ut-link-register--color-text ut-link-register--without-icons">
                        <div class="ut-link-register__link-list ">
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/einrichtungen/verwaltung-dezernate/ii-studium-und-lehre/zentrale-studienberatung-zsb.html" target="_self">Zentrale Studienberatung</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/footer/erste-spalte/advice-for-international-students.html" target="_self">Advise for International Students</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/studium/studienorganisation/studentensekretariat.html" target="_self">Infos und Formulare Studentensekretariat</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/zielgruppen/beschaeftigte/service/downloadbereich.html" target="_self">Forms Central Administration</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/einrichtungen/personalvertretungen-beratungsdienste-und-beauftragte/lageplaene.html" target="_self">Lagepläne</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/einrichtungen/personalvertretungen-beratungsdienste-und-beauftragte/lageplaene/behindertengerechte-aufgaenge.html" target="_self">Barrierefreie Zugänge</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/studium/verzeichnis-der-studiengaenge.html" target="_self">Verzeichnis der Studiengänge</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/footer/dritte-spalte/personensuche-epv.html" target="_self">Personensuche (EPV)</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ut-grid__col-2 ut-page-footer__col">
        <div class="ut-panel panel ut-panel--collapsing-only-mobile" id="footerpanel-2">
            <div class="ut-panel__heading ut-page-footer__heading" id="footerpanel-2-ph">
                <h6 class="ut-heading ut-panel__title"><a class="ut-link ut-panel__link" href="#footerpanel-2-pc" data-toggle="collapse" title="Panel öffnen/schließen">Weitere Angebote<span class="ut-link__icon ut-link__icon--right ut-panel__icon ut-icon ut-icon-down-dir"></span></a></h6>
            </div>
            <div class="ut-panel__collapse collapse" id="footerpanel-2-pc">
                <div class="ut-panel__body ">
                    <div class="ut-link-register ut-link-register--color-text ut-link-register--without-icons">
                        <div class="ut-link-register__link-list ">
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/einrichtungen/verwaltung-dezernate/ii-studium-und-lehre/tuebinger-zentrum-fuer-wissenschaftliche-weiterbildung.html" target="_self">Wissenschaftliche Weiterbildung</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/universitaet/campusleben/veranstaltungen/veranstaltungskalender.html" target="_self">Veranstaltungskalender der Uni</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/service/corporate-design/startseite.html" target="_self">CD-Vorlagen</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/einrichtungen/stabsstellen/hochschulkommunikation/tagungs-und-praesentationsmaterial.html" target="_self">Konferenzmaterialien</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/footer/zweite-spalte/mensamenue.html" target="_self">Mensamenü</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.zdv.uni-tuebingen.de/zustandsansicht.html" target="_self">Betriebszustand Netzwerk</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/einrichtungen/verwaltung-dezernate/vi-bau-sicherheit-und-umwelt/abteilung-3/emas-prozess-an-der-universitaet.html" target="_self">EMAS an der Uni Tübingen</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/universitaet/aktuelles-und-publikationen/newsletter-uni-tuebingen-aktuell/" target="_self">Newsletter Uni Tübingen aktuell</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ut-grid__col-3 ut-page-footer__col">
        <div class="ut-panel panel ut-panel--collapsing-only-mobile" id="footerpanel-3">
            <div class="ut-panel__heading ut-page-footer__heading" id="footerpanel-3-ph">
                <h6 class="ut-heading ut-panel__title"><a class="ut-link ut-panel__link" href="#footerpanel-3-pc" data-toggle="collapse" title="Panel öffnen/schließen">Portale &amp; Einrichtungen<span class="ut-link__icon ut-link__icon--right ut-panel__icon ut-icon ut-icon-down-dir"></span></a></h6>
            </div>
            <div class="ut-panel__collapse collapse" id="footerpanel-3-pc">
                <div class="ut-panel__body ">
                    <div class="ut-link-register ut-link-register--color-text ut-link-register--without-icons">
                        <div class="ut-link-register__link-list ">
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/footer/erste-spalte/campus-portal.html" target="_self">Campus-Portal</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/footer/zweite-spalte/katalog-universitaetsbibliothek.html" target="_self">Katalog Universitätsbibliothek</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/footer/zweite-spalte/webmail-uni-tuebingen.html" target="_self">Webmail Uni Tübingen</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="https://www.uni-tuebingen.de/index.php?id=167&L=&redirect_url=/index.php?id=167&L=" target="_self">LOGIN@UNI-TUEBINGEN</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/einrichtungen/informations-kommunikations-und-medienzentrum-ikm/e-learning-portal-elp/lernplattformen.html" target="_self">ILIAS, moodle, BSCW</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/footer/dritte-spalte/timms-video-portal.html" target="_self">Timms Video Portal</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/universitaet/campusleben/unishop.html" target="_self">Unishop</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ut-grid__col-4 ut-page-footer__col">
        <div class="ut-panel panel ut-panel--collapsing-only-mobile" id="footerpanel-4">
            <div class="ut-panel__heading ut-page-footer__heading" id="footerpanel-4-ph">
                <h6 class="ut-heading ut-panel__title"><a class="ut-link ut-panel__link" href="#footerpanel-4-pc" data-toggle="collapse" title="Panel öffnen/schließen">Kontakt<span class="ut-link__icon ut-link__icon--right ut-panel__icon ut-icon ut-icon-down-dir"></span></a></h6>
            </div>
            <div class="ut-panel__collapse collapse" id="footerpanel-4-pc">
                <div class="ut-panel__body ">
                    <address class="ut-page-footer__contact">
                        <strong>Eberhard Karls Universität Tübingen</strong><br>Geschwister-Scholl-Platz<br>72074 Tübingen<br>Tel: +49 (0) 7071 29-0<br>Fax: +49 (0) 7071 29-59 90<br><a href="mailto:info@uni-tuebingen.de" title="E-Mail senden">info [at] uni-tuebingen.de</a><br>
                    </address>
                    <div class="ut-spacer ut-spacer--s" role="separator"></div>
                    <a class="ut-link" href="#">Zum Kontaktformular</a>
                    <div class="ut-spacer ut-spacer--xs" role="separator"></div>
                    <a class="ut-link" href="#" title="RSS-Datei">RSS-Feed</a>
                    <div class="ut-spacer ut-spacer--xs" role="separator"></div>
                    <a href="http://www.facebook.de" title="" target="_blank" class="ut-link-social-media">
                        <span class="ut-link-social-media__icon ut-icon-facebook" role="img" aria-label="Facebook">
                            <span class="sr-only">Facebook</span>
                        </span>
                    </a>
                    <a href="http://www.twitter.de" title="" target="_blank" class="ut-link-social-media ">
                        <span class="ut-link-social-media__icon ut-icon-twitter" role="img" aria-label="Twitter">
                            <span class="sr-only">Twitter</span>
                        </span>
                    </a>
                    <a href="http://www.youtube.de" title="" target="_blank" class="ut-link-social-media ">
                        <span class="ut-link-social-media__icon ut-icon-youtube" role="img" aria-label="Youtube">
                            <span class="sr-only">Youtube</span>
                        </span>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<hr class="ut-page-footer__devider hidden-xs">

<div class="row ut-page-footer__legal">
    <div class="col-xs-12 col-sm-6 col-md-6 ut-page-footer__copyright">
        <p class="ut-copyright">© 2017 Eberhard Karls Universität Tübingen, Tübingen</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 ut-page-footer__nav-meta">
        <nav class="ut-nav ut-nav--meta-bottom" aria-label="Metanavigation">
            <ul class="ut-nav__list ">
                <li class="ut-nav__item " data-level-count="1">
                    <a class="ut-link ut-nav__link" href="#">Impressum</a>
                </li>
                <li class="ut-nav__item " data-level-count="2">
                    <a class="ut-link ut-nav__link" href="#">Datenschutzerklärung</a>
                </li>
                <li class="ut-nav__item " data-level-count="3">
                    <a class="ut-link ut-nav__link" href="?page=sitemap">Sitemap</a>
                </li>
            </ul>
        </nav>
    </div>
</div>
