<div class="ut-grid ut-grid--deck ut-grid--3333 ut-page-footer__quicklinks">
    <div class="ut-grid__col-1 ut-page-footer__col">
        <div class="ut-panel panel ut-panel--collapsing-only-mobile" id="footerpanel-1">
            <div class="ut-panel__heading ut-page-footer__heading" id="footerpanel-1-ph">
                <h6 class="ut-heading ut-panel__title"><a class="ut-link ut-panel__link" href="#footerpanel-1-pc" data-toggle="collapse" title="Panel öffnen/schließen">Service<span class="ut-link__icon ut-link__icon--right ut-panel__icon ut-icon ut-icon-down-dir"></span></a></h6>
            </div>
            <div class="ut-panel__collapse collapse" id="footerpanel-1-pc">
                <div class="ut-panel__body ">
                    <div class="ut-link-register ut-link-register--color-text ut-link-register--without-icons">
                        <div class="ut-link-register__link-list ">
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/international/welcome-center/registration.html" target="_self">Welcome Center for Scholars</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="" target="_self">Advice for International Students</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/studium/studienorganisation/studentensekretariat.html" target="_self">Infos und Formulare Studentensekretariat</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/zielgruppen/staff/service/downloadbereich.html" target="_self">Forms Central Administration</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/facilities/personalvertretungen-beratungsdienste-und-beauftragte/lageplaene.html" target="_self">Maps</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/facilities/personalvertretungen-beratungsdienste-und-beauftragte/lageplaene/disabled-access.html" target="_self">Barrierefreie Zugänge</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/study/degree-programs-available.html" target="_self">Courses available</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/footer/dritte-spalte/staff-search-epv.html" target="_self">Staff Search (EPV)</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ut-grid__col-2 ut-page-footer__col">
        <div class="ut-panel panel ut-panel--collapsing-only-mobile" id="footerpanel-2">
            <div class="ut-panel__heading ut-page-footer__heading" id="footerpanel-2-ph">
                <h6 class="ut-heading ut-panel__title"><a class="ut-link ut-panel__link" href="#footerpanel-2-pc" data-toggle="collapse" title="Panel öffnen/schließen">Weitere Angebote<span class="ut-link__icon ut-link__icon--right ut-panel__icon ut-icon ut-icon-down-dir"></span></a></h6>
            </div>
            <div class="ut-panel__collapse collapse" id="footerpanel-2-pc">
                <div class="ut-panel__body ">
                    <div class="ut-link-register ut-link-register--color-text ut-link-register--without-icons">
                        <div class="ut-link-register__link-list ">
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/zielgruppen/weiterbildung.html" target="_self">Wissenschaftliche Weiterbildung</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/university/campusleben/veranstaltungen/veranstaltungskalender.html" target="_self">Current events</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/service/corporate-design/startseite.html" target="_self">Corporate Design</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/facilities/stabsstellen/public-relations-departement/tagungs-und-praesentationsmaterial.html" target="_self">Conference Material</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/footer/zweite-spalte/mensa-menu.html" target="_self">Mensa menu</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/facilities/zentrum-fuer-datenverarbeitung/zustandsansicht.html" target="_self">Operating Status Network</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/facilities/verwaltung-dezernate/vi-bau-sicherheit-und-umwelt/abteilung-3/emas-prozess-an-der-universitaet.html" target="_self">EMAS Eco-Management</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/universitaet/aktuelles-und-publikationen/newsletter-uni-tuebingen-aktuell/" target="_self">Newsletter Uni Tübingen aktuell</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ut-grid__col-3 ut-page-footer__col">
        <div class="ut-panel panel ut-panel--collapsing-only-mobile" id="footerpanel-3">
            <div class="ut-panel__heading ut-page-footer__heading" id="footerpanel-3-ph">
                <h6 class="ut-heading ut-panel__title"><a class="ut-link ut-panel__link" href="#footerpanel-3-pc" data-toggle="collapse" title="Panel öffnen/schließen">Portale &amp; Einrichtungen<span class="ut-link__icon ut-link__icon--right ut-panel__icon ut-icon ut-icon-down-dir"></span></a></h6>
            </div>
            <div class="ut-panel__collapse collapse" id="footerpanel-3-pc">
                <div class="ut-panel__body ">
                    <div class="ut-link-register ut-link-register--color-text ut-link-register--without-icons">
                        <div class="ut-link-register__link-list ">
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/footer/erste-spalte/campus-portal.html" target="_self">Campus-Portal</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/footer/zweite-spalte/library-online-catalogue.html" target="_self">Library Online-catalogue</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/footer/zweite-spalte/webmail-uni-tuebingen.html" target="_self">Webmail Uni Tübingen</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="https://www.uni-tuebingen.de/nc/en/login/login.html?redirect_url=%2Findex.php%3Fid%3D167" target="_self">LOGIN@UNI-TUEBINGEN</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/facilities/informations-kommunikations-und-medienzentrum-ikm/e-learning-portal-elp/lernplattformen.html" target="_self">E-Learning</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/footer/dritte-spalte/timms-video-portal.html" target="_self">Timms Video Portal</a>
                            <a class="ut-link ut-link--internal ut-link--block" href="http://www.uni-tuebingen.de/en/university/unishop.html" target="_self">Unishop</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="ut-grid__col-4 ut-page-footer__col">
        <div class="ut-panel panel ut-panel--collapsing-only-mobile" id="footerpanel-4">
            <div class="ut-panel__heading ut-page-footer__heading" id="footerpanel-4-ph">
                <h6 class="ut-heading ut-panel__title"><a class="ut-link ut-panel__link" href="#footerpanel-4-pc" data-toggle="collapse" title="Panel öffnen/schließen">Contact<span class="ut-link__icon ut-link__icon--right ut-panel__icon ut-icon ut-icon-down-dir"></span></a></h6>
            </div>
            <div class="ut-panel__collapse collapse" id="footerpanel-4-pc">
                <div class="ut-panel__body ">
                    <address class="ut-page-footer__contact">
                        <strong>Tübingen University Library</strong><br>Wilhelmstr. 32<br>72074 Tübingen<br>Tel: +49 (0) 7071 29-72577<br><a href="mailto:gundert-portal@ub.uni-tuebingen.de" title="send email">gundert-portal@ub.uni-tuebingen.de</a><br>
                    </address>
                </div>
            </div>
        </div>
    </div>
</div>

<hr class="ut-page-footer__devider hidden-xs">

<div class="row ut-page-footer__legal">
    <div class="col-xs-12 col-sm-6 col-md-6 ut-page-footer__copyright">
        <p class="ut-copyright">© 2018 Eberhard Karls Universität Tübingen, Tübingen</p>
    </div>
    <div class="col-xs-12 col-sm-6 col-md-6 ut-page-footer__nav-meta">
        <nav class="ut-nav ut-nav--meta-bottom" aria-label="Metanavigation">
            <ul class="ut-nav__list ">
                <li class="ut-nav__item " data-level-count="1">
                    <a class="ut-link ut-nav__link" href="?page=imprint">Imprint</a>
                </li>
                <li class="ut-nav__item " data-level-count="2">
                    <a class="ut-link ut-nav__link" href="http://www.uni-tuebingen.de/impressum/datenschutzerklaerung.html">Datenschutzerklärung</a>
                </li>
                <li class="ut-nav__item " data-level-count="3">
                    <a class="ut-link ut-nav__link" href="?page=sitemap">Sitemap</a>
                </li>
            </ul>
        </nav>
    </div>
</div>
