<h1 class="ut-heading ut-heading--h1">###DT-help###</h1>
<h2 class="ut-heading ut-heading--h2">Search</h2>
<p>Once you have chosen a list of materials, you can use the search function to find specific results. The list of materials will change as soon as you begin to enter a term.<br/>
Attention: The search is carried out within the listed records of materials you have chosen and not within the full-texts of those materials.</p>

<h2 class="ut-heading ut-heading--h2">Sort</h2>
<p>In addition to a specific search, you can also sort the lists according to your interests. The default setting for each list is alphabetical sorting according to title. However, if you want to sort another column, e.g. the column 'Date', click on the small arrow <img src="/vendor/jquery-datatables/images/sort_both.png"/> to the right of the column you want to sort alphabetically (ascending or descending).<br/>
Sort two columns<br/>
For example: Sort the column "Date" (upwards or downwards). Now hold down the "shift" key and sort for example the column "Title". This gives you a list in which the titles of each publication year are sorted alphabetically.</p>
