<h1 class="ut-heading ut-heading--h1">###DT-help###</h1>

<h2 class="ut-heading ut-heading--h2">Suchen</h2>
<p>Sie können die Bestandslisten nach einem Wort(stamm) oder einem Autor durchsuchen und erhalten eine Liste, die dieses Wort / diesen Wortstamm enthält.<br/>
Achtung: Die Suche läuft nicht über den Volltext der Materialien, sondern nur über die Einträge, die in der jeweiligen Liste zu sehen sind!</p>

<h2 class="ut-heading ut-heading--h2">Sortieren</h2>
<p>Neben einer konkreten Suche können Sie die Listen auch nach Ihrem Interesse sortieren. Die Voreinstellung jeder Liste ist die alphabetische Sortierung nach dem Titel. Möchten sie jedoch eine andere Spalte sortieren, z.B. die Spalte ‚Datum‘, dann klicken Sie dazu auf den kleinen Pfeil <img src="/vendor/jquery-datatables/images/sort_both.png"/> rechts neben der Spalte, die Sie Alphabetisch (auf- oder absteigend) sortieren möchten.<br/>
Zwei Spalten sortieren<br/>
Sortieren Sie zum Beispiel die Spalte "Datum" (aufwärts oder abwärts). Halten Sie nun die "shift-Taste" gedrückt und sortieren z.B. die Spalte "Titel". Damit erhalten Sie eine Liste, auf der die Titel eines jeden Erscheinungsjahres alphabetisch sortiert sind.</p>
