<div class="ut-carousel carousel slide ut-carousel--decorate ut-carousel--decorate-color-brand-primary-1 ut-carousel--full-width" id="maincarousel" data-ride="carousel" data-interval="10000">
    <div class="ut-carousel__items" role="listbox">
        <div class="ut-carousel__item item active">
            <picture class="ut-picture ut-carousel__picture">
                <img src="img/home.png" class="ut-picture__img ut-carousel__img" alt="Platzhalterbild Picture" title="Zusätzliche Informationen zum Bild">
            </picture>
            <div class="ut-carousel__content ">
                <div class="ut-carousel__container ">
                    <a class="ut-carousel__link" href="#">
                        <div class="ut-carousel__caption ut-carousel__caption--align-right ut-carousel__caption--valign-bottom">
                            <h3 class="ut-heading ut-carousel__header">Das Hermann Gundert Portal</h3>
                            <p class="ut-carousel__text">der Universitätsbibliothek Tübingen</p>
                        </div>
                    </a>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="container">
    <h1 class="ut-heading ut-heading--h1">Hermann Gundert</h1>
    <p>Hermann Gundert (1814 - 1893) studierte Theologie in Tübingen, wo er auch Sanskrit lernte und 1835 zum Dr. phil promoviert wurde. In England lernte er dann weitere indische Sprachen, nämlich Bengali, Telugu, Marathi und Urdu. 1838 ging er im Auftrag der Basler Mission nach Nettur, wo Malayalam gesprochen wird. Auch diese Sprache eigente er sich rasch an und gründete eine Schule für die Erforschung des Malayalam. Er war es, der eine erste Grammatik des Malayalam verfasste sowie ein Malayalam-English Wörterbuch, das noch heute in Gebrauch ist. Zu seinen Pionierleistungen zählt auch die Einführung des 'cil' [   ] Zeichens in der Malayalam-Schrift sowie die orthografische Unterscheidung zwischen kurzem und langem 'e'.</p>
    <p>Als Missionar fühlte er sich berufen, die Bibel und andere religiöse Texte ins Malayalam zu übersetzen, aber auch vor literarischen Texten machte er nicht Halt und so birgt sein Nachlass eine große Bandbreite an verschiedenartigen Texten auf Malayalam und Kanaresisch.</p>
    <p>Aufgrund seiner schwachen Gesundheit musste er Indien 1859 für immer verlassen und zog nach Calw im Schwarzwald, wo er seine literarischen Tätigkeiten weiter entfaltete.</p>

    <h2 class="ut-heading ut-heading--h2">Der Nachlass</h2>
    <p>Die Vielfalt der Interessen von Gundert spiegeln sich in seinem Nachlass wider: die Sammlung umfasst Grammatiken, Fibeln und religiöse Texte. Aber Gunderts literarische Interessen und Unternehmungen gehen weit über diesen Rahmen hinaus und es wäre eine grobe Unterschätzung dieses Gelehrten, ihn auf diese beiden Bereiche zu reduzieren.</p>
    <p>Hermann Gundert versuchte vielmehr, eine ganze Kultur zu verstehen und literarisch zu erfassen, und so findet sich in seinem Nachlass das berühmte Werk <a target="_blank" href="http://idb.ub.uni-tuebingen.de/diglit/CiXIV270/">Indulekha</a> und <a target="_blank" href="http://idb.ub.uni-tuebingen.de/diglit/CiXIV137/">Kundalatā</a>, der erste Malayalam Roman. Neben den modernen literarischen Werken seiner Zeit, sammelte er auch alte Texte aus der Sanskrit- und Malayali-Tradition; so gibt es beispielsweise das Sanskritwerk <a target="_blank" href="http://idb.ub.uni-tuebingen.de/diglit/CiXIV36/">Vajrasūcī</a>, mit einem <a target="_blank" href="http://idb.ub.uni-tuebingen.de/diglit/CiXIV36b/">Malayalam Kommentar</a> oder Krsnagatha, eine bekannte poetische Beschreibung des Lebens Krishnas auf Malayalam und manch' weitere Überraschung.</p>
    <p>Besonders beschäftigt hat Gundert die Entstehungsgeschichte von Kerala, denn wir finden gleich mehrere Versionen von Kerala Pazhama / Keralolpatti ... <font color="red">[noch ergänzen]</font></p>
    <p>Im ans Malayalam-Sprachgebiet angrenzende Gebiet des Kanaresischen (Kannaḍa), wirkte neben Gundert hauptsächlich sein enger Vertrauter und Mitarbeiter Hermann Mögling. Dieser sammelte und edierte neben grammatischen und lexikalischen Werken auch literarische Texte. In seiner 'Bibliothekca Carnatica' sollten die wichtigsten Werke der Kannada Tradition erscheinen. Die Serie wurde nie vollendet, die ersten 5 Foliobände enthalten jedoch wichtige Texte zur religiösen und intellektuellen Geschichte Südindiens, etwa das Cannabasava Purana, eine Hagiographie des Dichters und religiösen Revolutionärs Basava, oder Karnataka Bharata, die äußerst populäre kanaresische Adaption des Mahabharata.</p>
    <p>Interessante Quellen nicht nur für Linguisten, sondern auch für Religions- und Kulturhistoriker dürften die verschiedenen Wörterbücher sein, die sich Nachlass befinden, kann man doch anhand von ihnen vortrefflich die Verschiebung im Verständnis bestimmter Begriffe nachvollziehen. Hier seien etwa die Kannada-Latein oder Malayalam-Latein Wörterbücher genannt, die für die Missionen im Gebiet von Mysore von unterschiedlichen Institutionen zusammengestellt worden waren.</p>
</div>
