<div id="c6" class="csc-default">
    <!--  Header: [begin] -->
    <div class="csc-header csc-header-n1"><h1 class="csc-firstHeader">Hermann Gundert</h1></div>
    <!--  Header: [end] -->

    <!--  Text: [begin] -->
    <p class="bodytext">Hermann Gundert (1814 - 1893) studied Theology in  Tübingen, where he also learned Sanskrit. Here he obtained his Dr. phil.  in 1835. Later he went to England and studied various Indian languages,  as Bengali, Telugu, Marathi, and Urdu.
    </p>
    <p class="bodytext">In 1838 he started working for the Basel Mission in  Nettur in a Malayalam-speaking area. He established a Malayalam school  and focused on the analysis of the Malayalam language: It was in fact  he, who wrote the first Malayalam Grammar - a copy of the first version  from 1851 belongs to this collection [CiXIV 35] and a Malayalam-English  Dictionary that is still in use [CiXIV 68]; among Gundert’s pioneering  contributions there is also the introduction of the use of the cil sign  (˘) into Malayalam script <i>[ref. to article by Wiki-media people]</i>–  and the differentiation between long “e” േ and short “e” െ. Moreover,  his role as missionery brought him to translate the bible in Malayalam  and other religious texts, such the books of psalms. Due to health  issues he left India in 1859, and brought forward his research interests  in the family village of Calw  </p>
    <!--  Text: [end] -->
</div>
<!--  CONTENT ELEMENT, uid:6/text [end] -->

<!--  CONTENT ELEMENT, uid:22/text [begin] -->
<div id="c22" class="csc-default">
    <!--  Header: [begin] -->
    <div class="csc-header csc-header-n2"><h1>Legacy</h1></div>
    <!--  Header: [end] -->

    <!--  Text: [begin] -->
    <div class="csc-textpic-text"><p class="bodytext">All Gundert’s  interests are mirrored in his legacy: Gundert’s collection entails both  grammars and primers as well as many religious texts. Yet, to frame the  missioner’s intellectual enterprise within these two topic, would be a  to misunderstand this great savant. He was trying to comprehend an  entire culture, and not just bits and bites, and indeed in his legacy,  we find also modern novels - such as the famous <i>Indulekha</i>, which is, along with <i>Kundalatā</i>  considered as the first Malayalam novel; in addition to the new  developments of the literary production at his time, he collected also  old texts of the Sanskritic and Malayali traditions – thus, part of his  legacy are, for instance, a copy of the Sanskrit text <i>Vajrasūcī</i>, with a Malayalam commentary, or the <i>Kṛṣṇagatha</i>, a well-known Malayalam traditional poetical narration of Kṛṣṇa life.
        </p>
        <p class="bodytext">Gundert was specially interested in the historical development of Kerala and so we find several copies of the&nbsp; <i>Kerala Pazhama</i> <i><i>and </i></i><i>Keralolpati.<br /></i>
        </p>
        <p class="bodytext">Among the Kannaḍa texts, there is the Bibliotheca  Carnatica, a series of editions, initiated by his colleague and freind  Hermann Mögling, that was meant to encompass the most important works of  the Kannaḍa traditions. The series was never finished, but the first 5  volumes entail texts that are fundamental to the religious and  intellectual history of South India, as the Viraśaiva hagiography of the  poet and religious revolutionary, Basava, the <i>Cannabasava Purāṇa</i> or the most popular Kannada adaptation of the Indian epic <i>Mahābhārata</i>, the <i>Karnata Bharata </i>of Kumāravyasa.
        </p>
        <p class="bodytext">A text that could be of great interest not only for  linguists, but also for the scholars of religious and cultural studies  are for sure the Latin-Kannaḍa / Kannaḍa-Latin Dictionaries compiled for  the Missions in Mysore.</p></div>
    <!--  Text: [end] -->
</div>
<!--  CONTENT ELEMENT, uid:22/text [end] -->

<!--  CONTENT ELEMENT, uid:23/text [begin] -->
<div id="c23" class="csc-default">
    <!--  Header: [begin] -->
    <div class="csc-header csc-header-n3"><h1>The texts</h1></div>
    <!--  Header: [end] -->

    <!--  Text: [begin] -->
    <p class="bodytext">The conditions of the Gundert-Portal were to  digitize all Malayalam-, Kannada and Tulu printed texts and manuscripts  which are in the possession of Tübingen university library. They are  mainly part of the Gundert legacy. Some texts, however, may not belong  to the Gundert legacy in a narrow sense but were considered suitable to  be added into this context. Also, there were added printed texts as well  as handwritten notes from Gundert and colleagues in German and English.
    </p>
    <p class="bodytext">All texts which were digitized for the Gundert-Portal will be made accessible under <a href="http://www.uni-tuebingen.de/en/facilities/university-library/searching-borrowing/digitised-collections/digisouthasia.html" title="Opens internal link in new window" target="_blank" class="internal-link-new-window">DigitalSouthAsia / Gundert-Portal</a>. Please note, that the presentaion site is under construction.  </p>
    <!--  Text: [end] -->
</div>