<h1 class="ut-heading ut-heading--h1">Impressum</h1>
<p>Impressum gem. §5 Telemediengesetz und §5 Rundfunkstaatsvertrag</p>
<table class="ut-table ut-table--striped">
    <tbody class="ut-table__body">
        <tr class="ut-table__row">
            <td class="ut-table__item ut-table__body__item">Dienstanbieter</td>
            <td class="ut-table__item ut-table__body__item">Universitätsbibliothek der Eberhard Karls Universität Tübingen</td>
        </tr>
        <tr class="ut-table__row">
            <td class="ut-table__item ut-table__body__item">Anschrift</td>
            <td class="ut-table__item ut-table__body__item">Universitätsbibliothek<br/>
                Wilhelmstraße 32<br/>
                72074 Tübingen</td>
        </tr>
        <tr class="ut-table__row">
            <td class="ut-table__item ut-table__body__item">Kontakt</td>
            <td class="ut-table__item ut-table__body__item">Gundert-Team der UB Tübingen<br/>
                <a href="mailto:gundert-portal@ub.uni-tuebingen.de">gundert-portal@ub.uni-tuebingen.de</a>
        </tr>
        <tr class="ut-table__row">
            <td class="ut-table__item ut-table__body__item">Rechtsform</td>
            <td class="ut-table__item ut-table__body__item">Die Universität Tübingen ist eine Körperschaft des öffentlichen Rechts. Sie wird durch die Rektorin Prof. Dr. Dr. h.c. (Dōshisha) Karla Pollmann (E-Mail: rektorin@uni-tuebingen.de) gesetzlich vertreten.</td>
        </tr>
        <tr class="ut-table__row">
            <td class="ut-table__item ut-table__body__item">Umsatzsteuer-Identifikationsnummer</td>
            <td class="ut-table__item ut-table__body__item">DE812383453</td>
        </tr>
        <tr class="ut-table__row">
            <td class="ut-table__item ut-table__body__item">Aufsichtsbehörde</td>
            <td class="ut-table__item ut-table__body__item">Ministerium für Wissenschaft, Forschung und Kunst Baden Württemberg</td>
        </tr>
        <tr class="ut-table__row">
            <td class="ut-table__item ut-table__body__item">Haftungshinweis</td>
            <td class="ut-table__item ut-table__body__item">Trotz sorgfältiger inhaltlicher Kontrolle übernehmen wir keine Haftung für die Inhalte externer Links. Für den Inhalt der verlinkten Seiten sind ausschließlich deren Betreiber verantwortlich.</td>
        </tr>
        <tr class="ut-table__row">
            <td class="ut-table__item ut-table__body__item">Inhaltlich Verantwortliche für das Informationsangebot des Hermann Gundert Portals gemäß §55 Abs. 2 RStV</td>
            <td class="ut-table__item ut-table__body__item">Regine Tobias (Direktorin der Universitätsbibliothek Tübingen)</td>
        </tr>
    </tbody>
</table>
