<h1 class="ut-heading ut-heading--h1">###PAGE_TITLE###</h1>
<p>Mehr als <a>10.000 Briefe und Notizen</a> von Hermann Gundert an verschiedene Adressaten, die im <a href="http://www.dla-marbach.de/en/archive/" target="_blank">Deutschen Literatur Archiv (DLA)</a> in Marbach/Neckar liegen, waren vor einigen Jahren von Dr. Albrecht Frenz transkribiert worden und konnten in das Portal übernommen werden. Wir hoffen zusammen mit dem DLA diese Briefe in einem zukünftigen Projekt digitalisieren zu können.</p>

<p><a href="/materials/letters/Briefe%20Hermann%20Gunderts%20von%201823-1893.zip">ZIP-Download</a></p>

<div id="gundert-contentmiddle"><!-- this container may not be empty --></div>
<script type="text/javascript">Gundert.Search('###PAGE_ID###', false);</script>
