<h1 class="ut-heading ut-heading--h1">###PAGE_TITLE###</h1>
<p>More than <a>10,000 letters and notes</a> by Hermann Gundert to various addressees in the <a href="http://www.dla-marbach.de/en/archive/" target="_blank">German Literature Archive (DLA)</a> in Marbach/Neckar were transcribed by Dr. Albrecht Frenz a few years ago and could be incorporated into the portal. Together with the DLA we hope to digitize these letters in a future project.</p>

<p><a href="/materials/letters/Briefe%20Hermann%20Gunderts%20von%201823-1893.zip">ZIP-Download</a></p>

<div id="gundert-contentmiddle"><!-- this container may not be empty --></div>
<script type="text/javascript">Gundert.Search('###PAGE_ID###', false);</script>
