<h1 class="ut-heading ut-heading--h1">###DT-material_by_genre###</h1>
<p>All the materials have been labelled with a few formal keywords which will allow you to quickly gain an overview of the different literary genres. We have divided them into 8 groups, of which the following contain more categories than those indicated in the title.</p>

###DT-records_archive### contains
<ul>
    <li>archival documents</li>
    <li>reports</li>
    <li>illustrations</li>
</ul>

###DT-religious_works### contains
<ul>
    <li>Predominantly Christian source texts (Bible) and Christian treatment of topics.</li>
    <li>A few texts on a non-Christian religion. Attention: the Indian (Hindu) literature is not to be found under this genre! Please choose one of the others for results, for example ‚Fiction‘.</li>
</ul>

###DT-grammars_and_dictionaries### contains
<ul>
    <li>grammars</li>
    <li>schoolbooks</li>
    <li>dictionaries</li>
</ul>

<p>It may happen that a title contains several generic keywords and will therefore be found in several lists.</p>
