<h1 class="ut-heading ut-heading--h1">###DT-material_by_genre###</h1>
<p>Das gesamte Material wurde mit einigen formalen Schlagwörtern gekennzeichnet, die es Ihnen erlauben sollen, die verschiedenen Literaturgattungen rasch zu überblicken. Diese haben wir in 8 Gruppen eingeteilt, von denen die folgenden mehr als nur das in der Überschrift bezeichnete enthalten:</p>

###DT-records_archive###
<ul class="ut-list">
    <li>Archivalien</li>
    <li>Berichte</li>
    <li>Illustrationen</li>
</ul>

###DT-religious_works###
<ul class="ut-list">
    <li>Überwiegend christliche Quellentexte (Bibel) und christlich gefärbte Behandlung von Themen.</li>
    <li>Vereinzelt vorkommende Literatur zu einer nichtchristlichen Religion. Achtung: die indische (hinduistische) Literatur ist nicht unter dieser Rubrik zu finden! Bitte wählen Sie eine der anderen Gattungen, z.B ‚Literatur‘.</li>
</ul>

###DT-grammars_and_dictionaries###
<ul class="ut-list">
    <li>Grammatiken</li>
    <li>Schulbücher</li>
    <li>Wörterbücher</li>
</ul>

<p>Es kann vorkommen, dass ein Titel mehrere Gattungsschlagwörter enthält und dadurch in mehreren Listen zu finden ist.</p>
