<h1 class="ut-heading ut-heading--h1">###DT-scope###</h1>
<p>Main aim of the project was to catalogue, scan, and make available as open source all the textual material that is part of the Gundert legacy.</p>
<p>Gundert legacy contains not only printed books and pamphlets in Malayalam, there are also palm leaf manuscripts, notebooks of Gundert as well as booklets in Tuḷu and Kannaḍa.</p>
<p><font color="red">In addition related 19th century prints and manuscripts from South India / in South Indian languages were included, even when not strictly belonging tot he Gundert legacy. Also, Gundert’s and his collaborator’s articles in English and German are included, again some articles not strictly belonging to the Gundert network but interesting nevertheless.</font></p>
