<h1 class="ut-heading ut-heading--h1">Mitarbeiterinnen und Mitarbeiter</h1>

<h2 class="ut-heading ut-heading--h2">Projektverantwortliche</h2>
<p>
    Dr. Marianne Dörr<br/>
    Dr. Gabriele Zeller<br/>
    Prof. Dr. Heike Oberlin
</p>

<h2 class="ut-heading ut-heading--h2">Wissenschaftliche Mitarbeiterinnen</h2>
<p>
    Dr. Elena Mucciarelli<br/>
    Olga Nowicka, M.A.<br/>
    Rebecca Weckenmann
</p>

<h2 class="ut-heading ut-heading--h2">IT Support</h2>
<p>
    Florian Wagner<br/>
    Mario Trojan, B.Sc.
</p>


<h1 class="ut-heading ut-heading--h1">Auswärtige Beraterinnen und Berater</h1>
<p>
    Dr. Albrecht Frenz und die Hermann-Gundert-Gesellschaft e.V.<br/>
    Dr. Ophira Gamliel<br/>
    Prof. B.A. Viveka Rai<br/>
    Prof. Madhavan Sreenathan<br/>
    Prof. Scaria Zacharia
</p>

<h1 class="ut-heading ut-heading--h1">Mitwirkende in Indien</h1>
<p>
    Abdul Lathief<br/>
    Akhil Krishnan S.<br/>
    Lidiya Joy<br/>
    Liju Jacob Kuriakose<br/>
    Manju C. Thomas<br/>
    Mukesh Kumar M.<br/>
    Narendran S.<br/>
    Nowfal Mubaraue M. M.<br/>
    Sreenath V. K.<br/>
    Sheena Kochunni<br/>
    Sidhique Kappan<br/>
    Sugeesh G. Subhrahmanyam<br/>
    Sunil Kumar<br/>
    Tijo P Mathew
</p>
