<h1 class="ut-heading ut-heading--h1">Mitarbeiterinnen und Mitarbeiter</h1>

<h2 class="ut-heading ut-heading--h2">Projektverantwortliche</h2>
<p>
    Dr. Marianne Dörr<br/>
    Dr. Gabriele Zeller<br/>
    Prof. Dr. Heike Oberlin
</p>

<h2 class="ut-heading ut-heading--h2">Wissenschaftliche Mitarbeiterinnen</h2>
<p>
    Dr. Elena Mucciarelli<br/>
    Olga Nowicka, M.A.<br/>
    Rebecca Weckenmann, B.A.<br/>
    Mareike Heinritz, M.A.
</p>

<h2 class="ut-heading ut-heading--h2">Digitalisierung und Bearbeitung</h2>
<h3 class="ut-heading ut-heading--h3">Digitalisierungszentrum</h3>
<p>
    Mireille Murkowski<br/>
    Dominik Manal<br/>
    Markus Schädle<br/>
    Reinhard Pütz<br/>
    Diane Dolezel<br/>
    Ursula Müller<br/>
    Johannes Krause<br/>
    Claudia Parhammer<br/>
    Hannah Laub<br/>
    Romaine Botzenhardt<br/>
    Daniel Heyer<br/>
    Stefan Stemmler<br/>
    Kathrin Stauber<br/>
    Annika Timmins<br/>
    Sabrina Schauerhammer<br/>
    Rieke Bastian
</p>
<h3 class="ut-heading ut-heading--h3">Restaurierungswerkstatt</h3>
<p>
    Rahel Dipper<br/>
    Lukas Bott
</p>
<h3 class="ut-heading ut-heading--h3">Bibliothekarische Unterstützung</h3>
<p>
    Ulrike Mehringer<br/>
    Eva Garvert<br/>
    Gisela Höh<br/>
    Maria Schille
</p>

<h2 class="ut-heading ut-heading--h2">IT Support</h2>
<p>
    Olaf Brandt, M.A.<br/>
    Florian Wagner, M.Sc.<br/>
    Mario Trojan, B.Sc.
</p>


<h1 class="ut-heading ut-heading--h1">Auswärtige Beraterinnen und Berater</h1>
<p>
    Dr. Albrecht Frenz und die Hermann-Gundert-Gesellschaft e.V.<br/>
    Dr. Ophira Gamliel<br/>
    Prof. B.A. Viveka Rai<br/>
    Prof. M. Sreenathan<br/>
    Prof. Scaria Zacharia
</p>

<h1 class="ut-heading ut-heading--h1">Mitwirkende in Indien</h1>
<p>
    Abdul Lathief V.<br/>
    Aditya Narayanan  (Schüler)<br/>
    Agnus Antony (Schüler)<br/>
    Ajay Balachandran<br/>
    Akhil Krishnan S.<br/>
    Ananthu P.A.  (Schüler)<br/>
    Anoop Narayanan<br/>
    Aswathi Varma <br/>
    Benjamin Varghese<br/>
    Cibu C. J.<br/>
    Deepa Sulekha<br/>
    Geetha Byju<br/>
    Godsee Blessmon<br/>
    Gopika G. (Schüler)<br/>
    Jayasree C<br/>
    Jibu Jacob<br/>
    Junaid P.V.<br/>
    Kannan Shanmugham<br/>
    Lidiya Joy<br/>
    Liju Jacob Kuriakose<br/>
    Manoj Ebenezer<br/>
    Manju Thomas<br/>
    Maria Antony  (Schüler)<br/>
    Mukesh Kumar<br/>
    Narendran S<br/>
    Nithin P.T. (Schüler)<br/>
    Nowfal Mubaraque<br/>
    Priya Nambudiri<br/>
    Rajesh Odayanchal<br/>
    Ramesh N G<br/>
    Renjith R R<br/>
    Rojy Pala<br/>
    Sai Ram (Schüler)<br/>
    Sheena Roy<br/>
    Shiju Alex<br/>
    Sidhique Kappan<br/>
    Sivakumar R P<br/>
    Sreenath<br/>
    Sriletha Pillai<br/>
    Sugeesh G Subrahmanyam<br/>
    Sunil V.S.<br/>
    Sunil G krishnan<br/>
    Sunil Kumar Elamkulam Muthukurussi<br/>
    Sunil Prabhakar<br/>
    Tijo P Mathew<br/>
    Tony Antony<br/>
    Viswaprabha
</p>
