<!DOCTYPE html>
<html lang="###LANGUAGE_CODE###" class="no-js mod_picture mod_localstorage mod_cssremunit mod_placeholder mod_srcset mod_mediaqueries mod_no-touchevents mod_formvalidation mod_flexbox mod_csstransitions js-state__ut-nav-is-closed">
    <head>
        <title>Hermann Gundert Portal</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">

        <!-- CSS includes (vendor) -->
        <link rel="stylesheet" type="text/css" href="vendor/ut/css/style.css" media="all">
        <link rel="stylesheet" type="text/css" href="vendor/ut/css/styleguide.min.css" media="all">
        <link rel="stylesheet" type="text/css" href="vendor/ut/css/prism-typeahead.min.css" media="all">
        <link rel="stylesheet" type="text/css" href="vendor/jquery-datatables/css/jquery.dataTables.min.css" media="all">
        <link rel="stylesheet" type="text/css" href="vendor/jquery-datatables-responsive/css/dataTables.responsive.css" media="all">

        <!-- CSS includes (local) -->
        <link rel="stylesheet" type="text/css" href="css/ut.fixes.local.css" media="all">
        <link rel="stylesheet" type="text/css" href="css/gundert.css" media="all">

        <!-- JS includes (vendor) -->
        <!-- jQuery -->
        <script src="vendor/jquery/jquery.min.js"></script>
        <script src="vendor/jquery-datatables/js/jquery.dataTables.min.js"></script>
        <script src="vendor/jquery-datatables-responsive/js/dataTables.responsive.min.js"></script>
        <script src="vendor/jquery-validation/jquery.validate.min.js"></script>

        <!-- Bootstrap -->
        <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
        <script src="vendor/bootstrap/js/carousel.js"></script>
        <script src="vendor/bootstrap/js/collapse.js"></script>
        <script src="vendor/bootstrap/js/dropdown.js"></script>
        <script src="vendor/bootstrap/js/popover.js"></script>
        <script src="vendor/bootstrap/js/tab.js"></script>
        <script src="vendor/bootstrap/js/tooltip.js"></script>
        <script src="vendor/bootstrap/js/transition.js"></script>

        <!-- ut dependencies (rest of UT is at bottom of page, needed to stay there because else we have problems with the navigation -->
        <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
        <script src="vendor/modernizr/modernizr.min.js"></script>
        <script src="vendor/popper/popper.js"></script>
        <script src="vendor/yepnope/yepnope-2.0.0.min.js"></script>

        <!-- JS includes (local) -->
        <script src="js/mappings.js"></script>
        <script src="js/gundert.js"></script>
        <script src="cache/displaytexts.js"></script>
    </head>
    <body>
        <!-- ###DOCUMENT### Start -->
        <div class="ut-page ut-page--layout-10">

            <!-- Header -->
            <header class="ut-page-header">
                <div class="container ut-page-header__container">
                    <div class="ut-page-header__menu">
                        <nav class="ut-page-header__switch ut-switchbar">
                            <ul class="ut-switchbar__list" role="tablist">

                                <!-- Language Switcher -->
                                <li class="ut-switchbar__item" id="switchbar-language">
                                    <a href="#" class="ut-switchbar__toggle" data-toggle="switchbar" data-target="#switchblock-language" title="Sprache wählen" role="button" aria-haspopup="true" aria-expanded="false">
                                        <span class="ut-switchbar__icon ut-icon ut-icon-globe"></span>
                                        <span class="ut-switchbar__label">###DT-language###</span>
                                    </a>
                                    <div class="ut-switchblock__item ut-switchblock__item--dropdown" id="switchblock-language" style="right: 40px;">
                                        <div class="ut-switchblock__header">
                                            <span class="ut-switchblock__title">###DT-language_chooser###</span>
                                            <span class="ut-switchblock__close-icon ut-icon ut-icon-cancel" role="button"></span>
                                        </div>
                                        <div class="ut-switchblock__content">
                                            <nav class="ut-nav ut-nav--language">
                                                <ul class="ut-nav__list ">
                                                    <li class="ut-nav__item " data-level-count="1">
                                                        <a class="ut-link ut-nav__link" href="###LANGUAGE_PICKER_DE###" title="Sprache Deutsch wählen">Deutsch</a>
                                                    </li>
                                                    <li class="ut-nav__item " data-level-count="2">
                                                        <a class="ut-link ut-nav__link" href="###LANGUAGE_PICKER_EN###" title="Sprache Englisch wählen">English</a>
                                                    </li>
                                                </ul>
                                            </nav>
                                        </div>
                                    </div>
                                </li>

                                <!-- Switchbar Menu (for low resolutions) -->
                                <li class="ut-switchbar__item" id="switchbar-menu">
                                    <a href="#" class="ut-switchbar__toggle" id="ut-identifier--menu-toggle" data-toggle="switchbar" data-target="#switchblock-menu" title="Sprache wählen" role="button" aria-haspopup="true" aria-expanded="false">
                                        <span class="ut-switchbar__icon ut-icon ut-icon-menu"></span>
                                        <span class="ut-switchbar__label sr-only-focusable">Menu</span>
                                    </a>
                                </li>

                            </ul>
                        </nav>
                    </div>
                    <div class="ut-page-header__banner">
			<div class="ut-page-header__logos">
                            <a href="" title="" class="ut-logo-link ut-logo-link--main ">
                                <img src="vendor/ut/img/Logo_Universitaet_Tuebingen.svg" class="ut-img ut-img--logo ut-img--logo-main " alt="Logo der Universität Tübingen" title="Zusätzliche Informationen zum Bild">
                            </a>
                            <a href="" title="" class="ut-logo-link ut-logo-link--excellence ">
                                <img src="vendor/ut/img/Logo_Universitaet_Tuebingen_Exzellent_###LANGUAGE_CODE_UPPER###.svg" class="ut-img ut-img--logo ut-img--logo-excellence-###LANGUAGE_CODE_LOWER### " alt="Logo Exzellenzinitiative der Universität Tübingen" title="Zusätzliche Informationen zum Bild">
                            </a>
                        </div>
                        <div class="ut-page-header__dropdowns"></div>
                    </div>
                    <div class="ut-page__switchblock ut-switchblock">
                        <div id="switchblock-menu" class="ut-switchblock__item">
                            <div class="ut-switchblock__header">
                                <span class="ut-switchblock__title">Menu</span>
                                <span class="ut-switchblock__close-icon ut-icon ut-icon-cancel" role="button"></span>
                            </div>

                            <div class="ut-switchblock__content">
                                <nav id="ut-identifier--main-nav" class="ut-nav ut-nav--main">
                                    <!-- ###TOPNAV### Start -->
                                    <ul class="ut-nav__list ut-nav__list--level-1 ">
                                        <li class="ut-nav__item ut-nav__item--level-1 " data-level-count="1">
                                            <div class="ut-nav__link-group ">
                                                <a class="ut-link ut-nav__link ut-nav__link--level-1" href="#" tabindex="0">Universität</a>					<a class="ut-nav__toggle-link" tabindex="-1" role="button" aria-label="-Menü aufklappen/zuklappen">
                                                <a class="ut-nav__toggle-link" tabindex="-1" role="button" aria-label="-Menü aufklappen/zuklappen">
                                                    <span class="ut-nav__toggle-line"></span>
                                                    <span class="ut-nav__toggle-icon"></span>
                                                </a>
                                            </div>

                                            <ul class="ut-nav__list ut-nav__list--level-2 ">
                                                <li class="ut-nav__item ut-nav__item--close-level">
                                                    <a href="#" class="ut-nav__link ut-nav__link--close-level">
                                                        <span class="ut-icon ut-icon-angle-left ut-nav__link-icon ut-nav__link-icon--left"></span>zurück
                                                    </a>
                                                </li>
                                                <li class="ut-nav__item ut-nav__item--area-title">
                                                    <a href="" class="ut-nav__link ut-nav__link--area-title" tabindex="0">Universität</a>
                                                </li>
                                            </ul>
                                        </li>
                                    </ul>
                                    <!-- ###TOPNAV### End -->
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content -->
            <div class="ut-page__main" role="main">

                <!-- Middle Column -->
                <div class="ut-wrapper">
                    <!-- ###CONTENTMIDDLE### Start -->
                    <!--<h1>###TITLE###</h1>-->
                    <!--You are here: ###BREADCRUMB###-->
                    <h1>Middle Column - Element 1</h1>
                    <p>Lorem Ipsum...</p>
                    <!-- ###CONTENTMIDDLE### End -->
                </div>

                <!-- Content End -->
            </div>

            <!-- Footer -->
            <footer class="ut-page__footer ut-page-footer " id="ut-identifier--footer">
                <!-- ###FOOTER### Start -->
                <h1>Footer</h1>
                <!-- ###FOOTER### End -->
            </footer>
        </div>
        <!-- ###DOCUMENT### End -->

        <!-- ut => MUST BE AT END OF PAGE, ELSE WE HAVE PROBLEMS RENDERING/EXTENDING THE NAVIGATION -->
        <script src="vendor/ut/js/polyfill.js"></script>
        <script src="vendor/ut/js/viewport.js"></script>
        <script src="vendor/ut/js/multi-carousel.js"></script>
        <script src="vendor/ut/js/nav.js"></script>
        <script src="vendor/ut/js/reorganize.js"></script>
        <script src="vendor/ut/js/switchbar.js"></script>
        <script src="vendor/ut/js/lightbox.js"></script>
        <script src="vendor/ut/js/include.js"></script>
        <script src="vendor/ut/js/only-patternlab.js"></script>
    </body>
</html>

