<!DOCTYPE html>
<html lang="###LANGUAGE_CODE###" class="no-js mod_picture mod_localstorage mod_cssremunit mod_placeholder mod_srcset mod_mediaqueries mod_no-touchevents mod_formvalidation mod_flexbox mod_csstransitions js-state__ut-nav-is-closed">
    <head>
        <title>###DT-site_title### - ###PAGE_TITLE###</title>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon">

        <!-- CSS includes (vendor) -->
        <link rel="stylesheet" type="text/css" href="vendor/ut-typo3/css/merged.css" media="all">
        <link rel="stylesheet" type="text/css" href="vendor/ut-typo3/css/ut.fixes.local.css" media="all">
        <link rel="stylesheet" type="text/css" href="vendor/jquery-datatables/css/jquery.dataTables.min.css" media="all">
        <link rel="stylesheet" type="text/css" href="vendor/jquery-datatables-responsive/css/dataTables.responsive.css" media="all">

        <!-- CSS includes (local) -->
        <link rel="stylesheet" type="text/css" href="css/gundert.css" media="all">

        <!-- JS includes (vendor) -->
        <!-- jQuery -->
        <script src="vendor/jquery/jquery.min.js"></script>
        <script src="vendor/jquery-datatables/js/jquery.dataTables.min.js"></script>
        <script src="vendor/jquery-datatables-responsive/js/dataTables.responsive.min.js"></script>
        <script src="vendor/jquery-keytable/dataTables.keyTable.min.js"></script>
        <script src="vendor/jquery-validation/jquery.validate.min.js"></script>

        <!-- Bootstrap -->
        <script src="vendor/bootstrap/js/bootstrap.min.js"></script>
        <script src="vendor/bootstrap/js/carousel.js"></script>
        <script src="vendor/bootstrap/js/collapse.js"></script>
        <script src="vendor/bootstrap/js/dropdown.js"></script>
        <script src="vendor/bootstrap/js/popover.js"></script>
        <script src="vendor/bootstrap/js/tab.js"></script>
        <script src="vendor/bootstrap/js/tooltip.js"></script>
        <script src="vendor/bootstrap/js/transition.js"></script>

        <!-- ut dependencies (rest of UT is at bottom of page, needed to stay there because else we have problems with the navigation -->
        <script src="vendor/ut-typo3/js/merged_top.js"></script>
        <script src="vendor/magnific-popup/jquery.magnific-popup.min.js"></script>
        <script src="vendor/modernizr/modernizr.min.js"></script>
        <script src="vendor/popper/popper.js"></script>
        <script src="vendor/yepnope/yepnope-2.0.0.min.js"></script>

        <!-- JS includes (local) -->
        <!-- Increase version number to force browser reload if necessary -->
        <script src="js/mappings.js?v=2"></script>
        <script src="js/gundert.js?v=3"></script>
        <script src="cache/displaytexts.js"></script>
    </head>
    <body>
        <!-- ###DOCUMENT### Start -->
        <div class="ut-page ut-page--layout-10">

            <!-- Header -->
            <header class="ut-page__header ut-page-header">
                <nav class="ut-nav ut-nav--skipanchors" aria-label="Bereiche überspringen">
                    <ul class="ut-nav__list">
                        <li class="ut-nav__item" data-level-count="1">
                            <a class="ut-link ut-nav__link hidden-xs hidden-sm sr-only sr-only-focusable" href="#ut-identifier--main-nav" tabindex="0">Direkt zur Hauptnavigation</a>
                        </li>
                        <li class="ut-nav__item" data-level-count="2">
                            <a class="ut-link ut-nav__link sr-only sr-only-focusable" href="#ut-identifier--main-content" tabindex="0">Direkt zum Inhalt</a>
                        </li>
                        <li class="ut-nav__item" data-level-count="3">
                            <a class="ut-link ut-nav__link sr-only sr-only-focusable" href="#ut-identifier--footer" tabindex="0">Direkt zur Fussleiste</a>
                        </li>
                    </ul>
                </nav>
                <div class="container ut-page-header__container">
                    <div class="ut-page-header__menu">
                        <nav class="ut-page-header__switch ut-switchbar">
                            <ul class="ut-switchbar__list" role="tablist">

                                <!-- Help -->
                                <li class="ut-switchbar__item" id="switchbar-help">
                                    <a href="/?page=help" class="ut-switchbar__toggle" data-toggle="switchbar" data-target="#switchblock-help" title="###DT-help###" role="button" aria-haspopup="false" aria-expanded="false">
                                        <span class="ut-switchbar__icon ut-icon ut-icon-info-circled"></span>
                                        <span class="ut-switchbar__label">###DT-help###</span>
                                    </a>
                                </li>

                                <!-- Language Switcher -->
                                <li class="ut-switchbar__item" id="switchbar-language">
                                    <a href="#" class="ut-switchbar__toggle" data-toggle="switchbar" data-target="#switchblock-language" title="###DT-language###" role="button" aria-haspopup="true" aria-expanded="false">
                                        <span class="ut-switchbar__icon ut-icon ut-icon-globe"></span>
                                        <span class="ut-switchbar__label">###DT-language###</span>
                                    </a>
                                    <div class="ut-switchblock__item ut-switchblock__item--dropdown" id="switchblock-language" style="right: 40px;">
                                        <div class="ut-switchblock__header">
                                            <span class="ut-switchblock__title">###DT-language_chooser###</span>
                                            <span class="ut-switchblock__close-icon ut-icon ut-icon-cancel" role="button"></span>
                                        </div>
                                        <div class="ut-switchblock__content">
                                            <nav class="ut-nav ut-nav--language">
                                                <ul class="ut-nav__list">
                                                    <li class="ut-nav__item" data-level-count="1">
                                                        <a class="ut-link ut-nav__link" href="###LANGUAGE_PICKER_DE###" title="Sprache Deutsch wählen">Deutsch</a>
                                                    </li>
                                                    <li class="ut-nav__item" data-level-count="2">
                                                        <a class="ut-link ut-nav__link" href="###LANGUAGE_PICKER_EN###" title="Sprache Englisch wählen">English</a>
                                                    </li>
                                                </ul>
                                            </nav>
                                        </div>
                                    </div>
                                </li>

                                <!-- Switchbar Menu (for low resolutions) -->
                                <li class="ut-switchbar__item" id="switchbar-menu">
                                    <a href="#" class="ut-switchbar__toggle" id="ut-identifier--menu-toggle" data-toggle="switchbar" data-target="#switchblock-menu" title="Sprache wählen" role="button" aria-haspopup="true" aria-expanded="false">
                                        <span class="ut-switchbar__icon ut-icon ut-icon-menu"></span>
                                        <span class="ut-switchbar__label sr-only-focusable">Menu</span>
                                    </a>
                                </li>

                            </ul>
                        </nav>
                    </div>
                    <div class="ut-page-header__banner">
			<div class="ut-page-header__logos">
                            <a href="https://www.uni-tuebingen.de" title="" class="ut-logo-link ut-logo-link--main">
                                <img src="vendor/ut-typo3/img/Logo_Universitaet_Tuebingen.svg" class="ut-img ut-img--logo ut-img--logo-main" alt="Logo der Universität Tübingen">
                            </a>
                            <a href="https://www.uni-tuebingen.de/exzellenzinitiative/" title="" class="ut-logo-link ut-logo-link--excellence">
                                <img src="vendor/ut-typo3/img/Logo_Universitaet_Tuebingen_Exzellent_EN.svg" class="ut-img ut-img--logo ut-img--logo-excellence-###LANGUAGE_CODE_LOWER###" alt="Logo Exzellenzinitiative der Universität Tübingen">
                            </a>
                        </div>
                        <div class="ut-page-header__dropdowns"></div>
                    </div>
                    <nav class="ut-nav-area ut-page-header__area_nav" aria-label="Bereichsnavigation">
                        <h4 class="ut-heading ut-nav-area__prev-level">
                            <a href="https://www.ub.uni-tuebingen.de" title="###DT-university_library###" class="ut-link ut-nav-area__link ut-nav-area__link--prev">
                                ###DT-university_library###
                            </a>
                        </h4>
                        <h2 class="ut-heading ut-nav-area__current-level">
                            <a class="ut-link ut-nav-area__link" title="###DT-site_title###" href="/">
                                ###DT-site_title###
                            </a>
                        </h2>
                    </nav>
                    <div class="ut-page__switchblock ut-switchblock">
                        <div id="switchblock-menu" class="ut-switchblock__item">
                            <div class="ut-switchblock__header">
                                <span class="ut-switchblock__title">Menu</span>
                                <span class="ut-switchblock__close-icon ut-icon ut-icon-cancel" role="button"></span>
                            </div>

                            <div class="ut-switchblock__content" data-breadcrumbuids="0">
                                <nav id="ut-identifier--main-nav" class="ut-nav ut-nav--main lory-slider js_variablewidth variablewidth" data-current-languageuid="###LANGUAGE_UID###">
                                    <div class="lory-frame js_frame">
                                        <!-- ###TOPNAV### Start -->
                                        <ul class="ut-nav__list ut-nav__list--level-1 lory-slides js_slides">
                                            <li class="ut-nav__item ut-nav__item--level-1" data-level-count="1">
                                                <div class="ut-nav__link-group">
                                                    <a class="ut-link ut-nav__link ut-nav__link--level-1" href="#" tabindex="0">Universität</a>
                                                    <a class="ut-nav__toggle-link" tabindex="-1" role="button" aria-label="-Menü aufklappen/zuklappen">
                                                        <span class="ut-nav__toggle-line"></span>
                                                        <span class="ut-nav__toggle-icon"></span>
                                                    </a>
                                                </div>

                                                <ul class="ut-nav__list ut-nav__list--level-2">
                                                    <li class="ut-nav__item ut-nav__item--close-level">
                                                        <a href="#" class="ut-nav__link ut-nav__link--close-level">
                                                            <span class="ut-icon ut-icon-angle-left ut-nav__link-icon ut-nav__link-icon--left"></span>zurück
                                                        </a>
                                                    </li>
                                                    <li class="ut-nav__item ut-nav__item--area-title">
                                                        <a href="" class="ut-nav__link ut-nav__link--area-title" tabindex="0">Universität</a>
                                                    </li>
                                                </ul>
                                            </li>
                                        </ul>
                                        <!-- ###TOPNAV### End -->
                                    </div>
                                </nav>
                            </div>
                        </div>
                    </div>
                </div>
            </header>

            <!-- Content -->
            <div id="ut-identifier--main-content" class="ut-page__main" role="main">

                <!-- Middle Column -->
                <div class="ut-wrapper">
                    <!-- ###CONTENTMIDDLE### Start -->
                    <!--<h1 class="ut-heading ut-heading--h1">###TITLE###</h1>-->
                    <!--You are here: ###BREADCRUMB###-->
                    <h1 class="ut-heading ut-heading--h1">Middle Column - Element 1</h1>
                    <p>Lorem Ipsum...</p>
                    <!-- ###CONTENTMIDDLE### End -->
                </div>

                <!-- Content End -->
            </div>

            <!-- Footer -->
            <footer id="ut-identifier--footer" class="ut-page__footer ut-page-footer">
                <!-- ###FOOTER### Start -->
                <h1 class="ut-heading ut-heading--h1">Footer</h1>
                <!-- ###FOOTER### End -->
            </footer>
        </div>
        <!-- ###DOCUMENT### End -->

        <!-- ut => MUST BE AT END OF PAGE, ELSE WE HAVE PROBLEMS RENDERING/EXTENDING THE NAVIGATION -->
        <script src="vendor/ut-typo3/js/merged_bottom.js"></script>

        ###MATOMO###
    </body>
</html>

